import type { ProcessedBook } from '../types/schema';

// Sample book data for testing the interface
export const sampleBooks: ProcessedBook[] = [
  {
    id: 'sample-1',
    metadata: {
      id: 'sample-1',
      title: 'The Art of Clear Thinking',
      author: 'Marcus Aurelius Johnson',
      isbn: '978-0123456789',
      publicationYear: 2023,
      genre: 'Self-Development',
      category: 'business',
      language: 'en',
      pageCount: 240,
      wordCount: 65000,
      readingLevel: 8.5,
      sourceFormat: 'pdf',
      processingDate: '2024-01-15T10:30:00Z',
      processingVersion: '1.0.0',
      estimatedReadingTimeMinutes: 260,
      tags: ['productivity', 'thinking', 'decision-making'],
    },
    originalVersion: {
      metadata: {} as any,
      voiceAnalysis: {} as any,
      chapters: [
        {
          id: 'ch1-orig',
          number: 1,
          title: 'The Foundation of Clear Thought',
          summary: 'Introduction to the principles of clear thinking',
          keyPoints: ['Mental models', 'Cognitive biases', 'Decision frameworks'],
          wordCount: 3200,
          sectionIds: ['sec1-orig'],
          paragraphIds: ['p1-orig', 'p2-orig', 'p3-orig'],
          imageIds: [],
          difficulty: 'beginner',
        },
      ],
      sections: [
        {
          id: 'sec1-orig',
          chapterId: 'ch1-orig',
          title: 'Introduction',
          orderIndex: 0,
          paragraphIds: ['p1-orig', 'p2-orig', 'p3-orig'],
          type: 'introduction',
        },
      ],
      paragraphs: [
        {
          id: 'p1-orig',
          chapterId: 'ch1-orig',
          sectionId: 'sec1-orig',
          orderIndex: 0,
          content: 'Clear thinking is one of the most important skills you can develop in life. It affects every decision you make, every problem you solve, and every opportunity you evaluate. However, most people never learn how to think clearly because they assume it comes naturally.',
          wordCount: 45,
          type: 'text',
          importance: 'high',
          concepts: ['clear thinking', 'decision making', 'problem solving'],
          technicalTerms: [],
          citations: [],
        },
        {
          id: 'p2-orig',
          chapterId: 'ch1-orig',
          sectionId: 'sec1-orig',
          orderIndex: 1,
          content: 'The reality is that clear thinking is a skill that must be developed through practice and deliberate effort. It requires understanding common mental traps, learning to recognize biases, and developing systematic approaches to complex problems.',
          wordCount: 38,
          type: 'text',
          importance: 'high',
          concepts: ['skill development', 'mental traps', 'biases', 'systematic thinking'],
          technicalTerms: ['cognitive biases'],
          citations: [],
        },
        {
          id: 'p3-orig',
          chapterId: 'ch1-orig',
          sectionId: 'sec1-orig',
          orderIndex: 2,
          content: 'In this book, we will explore the fundamental principles of clear thinking, examine the most common obstacles that prevent us from thinking clearly, and provide practical tools and techniques that you can use to improve your decision-making abilities.',
          wordCount: 42,
          type: 'text',
          importance: 'medium',
          concepts: ['principles', 'obstacles', 'tools', 'techniques'],
          technicalTerms: [],
          citations: [],
        },
      ],
      images: [],
      tableOfContents: [],
      citations: [],
    },
    rewrittenVersion: {
      metadata: {} as any,
      voiceAnalysis: {
        averageSentenceLength: 18.5,
        vocabularyComplexity: 'moderate',
        toneDescriptors: ['instructional', 'authoritative', 'accessible'],
        rhetoricalDevices: ['metaphor', 'repetition'],
        perspective: 'third-person',
        formalityLevel: 6,
        technicalityLevel: 4,
        personalityTraits: ['analytical', 'practical', 'encouraging'],
        styleFingerprint: 'Clear, direct instructional voice with practical examples',
      },
      chapters: [
        {
          id: 'ch1-rewritten',
          number: 1,
          title: 'The Foundation of Clear Thought',
          summary: 'Introduction to the principles of clear thinking with enhanced clarity',
          keyPoints: ['Mental models', 'Cognitive biases', 'Decision frameworks'],
          wordCount: 3400,
          sectionIds: ['sec1-rewritten'],
          paragraphIds: ['p1-rewritten', 'p2-rewritten', 'p3-rewritten'],
          imageIds: [],
          difficulty: 'beginner',
        },
      ],
      sections: [
        {
          id: 'sec1-rewritten',
          chapterId: 'ch1-rewritten',
          title: 'Introduction',
          orderIndex: 0,
          paragraphIds: ['p1-rewritten', 'p2-rewritten', 'p3-rewritten'],
          type: 'introduction',
        },
      ],
      paragraphs: [
        {
          id: 'p1-rewritten',
          chapterId: 'ch1-rewritten',
          sectionId: 'sec1-rewritten',
          orderIndex: 0,
          content: 'Clear thinking stands as one of life\'s most valuable skills. It shapes every decision you make, influences how you solve problems, and determines how well you evaluate opportunities. Yet despite its importance, most people never formally learn this skill—they mistakenly believe it develops naturally.',
          wordCount: 48,
          type: 'text',
          importance: 'high',
          concepts: ['clear thinking', 'decision making', 'problem solving', 'skill development'],
          technicalTerms: [],
          citations: [],
        },
        {
          id: 'p2-rewritten',
          chapterId: 'ch1-rewritten',
          sectionId: 'sec1-rewritten',
          orderIndex: 1,
          content: 'The truth is that clear thinking requires deliberate development. Like any valuable skill, it improves through focused practice and systematic learning. This development involves three key areas: recognizing mental traps that cloud judgment, identifying personal biases that skew reasoning, and mastering structured approaches to complex challenges.',
          wordCount: 52,
          type: 'text',
          importance: 'high',
          concepts: ['skill development', 'mental traps', 'cognitive biases', 'systematic approaches'],
          technicalTerms: ['cognitive biases'],
          citations: [],
        },
        {
          id: 'p3-rewritten',
          chapterId: 'ch1-rewritten',
          sectionId: 'sec1-rewritten',
          orderIndex: 2,
          content: 'This book provides a comprehensive guide to developing clear thinking. You\'ll discover the core principles that underpin effective reasoning, learn to identify the most common obstacles that muddy our thinking, and master practical tools that will sharpen your decision-making abilities for life.',
          wordCount: 47,
          type: 'text',
          importance: 'medium',
          concepts: ['principles', 'obstacles', 'practical tools', 'decision-making'],
          technicalTerms: [],
          citations: [],
        },
      ],
      images: [],
      tableOfContents: [],
      citations: [],
    },
    mappings: [
      {
        id: 'map1',
        originalParagraphIds: ['p1-orig'],
        rewrittenParagraphId: 'p1-rewritten',
        mappingType: '1:1',
        improvementTypes: ['clarity', 'flow'],
        confidenceScore: 92,
        qualityMetrics: {
          voicePreservationScore: 88,
          clarityImprovementScore: 85,
          factualAccuracyScore: 100,
          readabilityImprovement: 2.3,
          lengthChangePercentage: 6.7,
          technicalAccuracyScore: 100,
        },
        reviewNotes: 'Enhanced flow and clarity while maintaining author voice',
        humanReviewRequired: false,
      },
      {
        id: 'map2',
        originalParagraphIds: ['p2-orig'],
        rewrittenParagraphId: 'p2-rewritten',
        mappingType: '1:1',
        improvementTypes: ['expansion', 'clarity', 'structure'],
        confidenceScore: 89,
        qualityMetrics: {
          voicePreservationScore: 90,
          clarityImprovementScore: 88,
          factualAccuracyScore: 100,
          readabilityImprovement: 3.1,
          lengthChangePercentage: 36.8,
          technicalAccuracyScore: 100,
        },
        reviewNotes: 'Expanded content with better structure and examples',
        humanReviewRequired: false,
      },
      {
        id: 'map3',
        originalParagraphIds: ['p3-orig'],
        rewrittenParagraphId: 'p3-rewritten',
        mappingType: '1:1',
        improvementTypes: ['clarity', 'engagement'],
        confidenceScore: 91,
        qualityMetrics: {
          voicePreservationScore: 87,
          clarityImprovementScore: 83,
          factualAccuracyScore: 100,
          readabilityImprovement: 1.8,
          lengthChangePercentage: 11.9,
          technicalAccuracyScore: 100,
        },
        reviewNotes: 'Improved engagement and clarity',
        humanReviewRequired: false,
      },
    ],
    processingReport: {
      totalProcessingTimeMs: 45000,
      phaseDurations: {
        ingestion: 2000,
        analysis: 8000,
        planning: 5000,
        rewriting: 25000,
        qualityAssurance: 5000,
      },
      statisticsOriginal: {
        wordCount: 125,
        paragraphCount: 3,
        sentenceCount: 8,
        averageWordsPerSentence: 15.6,
        averageWordsPerParagraph: 41.7,
        readabilityScore: 7.2,
        complexityScore: 6.5,
        technicalTermCount: 1,
      },
      statisticsRewritten: {
        wordCount: 147,
        paragraphCount: 3,
        sentenceCount: 9,
        averageWordsPerSentence: 16.3,
        averageWordsPerParagraph: 49.0,
        readabilityScore: 8.1,
        complexityScore: 6.8,
        technicalTermCount: 1,
      },
      improvementsSummary: {
        clarityImprovements: 3,
        condensationCount: 0,
        expansionCount: 1,
        flowImprovements: 2,
        terminologyDefinitions: 0,
        exampleAdditions: 1,
        overallQualityScore: 89,
      },
      errorLog: [],
      warningLog: [],
    },
    qualityReport: {
      overallScore: 89,
      voicePreservation: {
        score: 88,
        analysis: 'Author voice well preserved with slight enhancement in clarity',
        riskAreas: ['Slightly more formal tone in places'],
      },
      contentIntegrity: {
        score: 98,
        factualAccuracy: 100,
        informationLoss: 0,
        citationPreservation: 100,
      },
      improvementEffectiveness: {
        clarityGain: 85,
        readabilityImprovement: 12.5,
        lengthOptimization: 17.6,
        flowEnhancement: 82,
      },
      mappingQuality: {
        accuracy: 95,
        completeness: 100,
        userExperienceScore: 91,
      },
      humanReviewRecommendations: [],
      confidenceInterval: [85, 93],
    },
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
    version: '1.0.0',
  },
];

// Utility function to add sample data to the database
export async function addSampleData() {
  const { db } = await import('./database');
  
  for (const book of sampleBooks) {
    await db.addBook(book);
  }
  
  console.log('Sample data added successfully');
}